"""doc_evolver.py — evolutionary JSDoc optimizer for undocumented methods.

Finds blind spots (undocumented public methods) via AST audit, generates
JSDoc variants using mutation strategies (LENGTH, STRUCTURE, KEYWORD_DENSITY,
POSITION), and evolves them against a retrieval fitness function: each
variant is patched into the code, the index is rebuilt, and a natural-language
query is run to score Recall@1. The winning variant is promoted through
generations of mutation, then patched back into the source.

Example:
    >>> from neuralmind.doc_evolver import DocEvolver, BlindSpot
    >>> spots = [BlindSpot(name="handleCSVExport", file_path="src/export.ts", line=42)]
    >>> evolver = DocEvolver(project_path=".", blind_spots=spots)
    >>> results = evolver.evolve()
    >>> for r in results:
    ...     print(f"{r.name}: fitness={r.best_fitness:.3f}")

See Also:
    - ``neuralmind/tuner.py`` — population-based evolutionary search (C3)
    - ``neuralmind/probe.py`` — label-free retrieval self-probe
    - ``tests/test_doc_evolver.py`` — test cases and usage patterns
    - ``docs/wiki/Architecture.md#doc-evolver`` — high-level design

Version:
    0.53.0
"""

from __future__ import annotations

import json
import logging
import os
import random
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)


# ----------------------------------------------------------------------- #
# Constants
# ----------------------------------------------------------------------- #

MAX_GENERATIONS = 5
POPULATION_SIZE = 5
HYSTERESIS = 0.05

# Mutation strategy weights for sampling
MUTATION_WEIGHTS = {
    "LENGTH": 0.3,
    "STRUCTURE": 0.3,
    "KEYWORD_DENSITY": 0.25,
    "POSITION": 0.15,
}

# JSDoc length variants
LENGTH_VARIANTS = {
    "short": 1,  # 1-line
    "medium": 3,  # 3-line
    "long": 5,  # 5-line
}

# JSDoc structure variants
STRUCTURE_VARIANTS = [
    "args_returns",  # Args/Returns/Raises
    "prose_only",  # prose-only
    "mixed",  # mixed
]


# ----------------------------------------------------------------------- #
# Dataclasses
# ----------------------------------------------------------------------- #


class MutationStrategy(Enum):
    """Mutation strategies for JSDoc variant generation."""

    LENGTH = "LENGTH"
    STRUCTURE = "STRUCTURE"
    KEYWORD_DENSITY = "KEYWORD_DENSITY"
    POSITION = "POSITION"


@dataclass
class BlindSpot:
    """A method lacking documentation — the target for JSDoc evolution.

    Args:
        name: Method name (e.g. ``"handleCSVExport"``).
        file_path: Path to the source file (relative to project root).
        line: 1-based line number where the method is defined.
        method_type: Kind of method — ``"function"``, ``"arrow"``, ``"method"``.
        params: List of parameter names, if known.
    """

    name: str
    file_path: str
    line: int
    method_type: str = "function"
    params: list[str] = field(default_factory=list)


@dataclass
class JSDocVariant:
    """A single JSDoc candidate generated by mutation.

    Args:
        strategy: The mutation strategy that produced this variant.
        lines: The JSDoc lines (without ``/**`` / ``*/`` delimiters).
        length_class: ``"short"``, ``"medium"``, or ``"long"``.
        structure: ``"args_returns"``, ``"prose_only"``, or ``"mixed"``.
        keyword_density: ``"synonyms"`` or ``"generic"``.
        position: ``"above"`` or ``"inline"``.
    """

    strategy: MutationStrategy
    lines: list[str]
    length_class: str = "medium"
    structure: str = "args_returns"
    keyword_density: str = "synonyms"
    position: str = "above"

    @property
    def text(self) -> str:
        """Render the variant as a complete JSDoc comment block."""
        if not self.lines:
            return ""
        body = "\n".join(f" * {line}" if line.strip() else " *" for line in self.lines)
        return f"/**\n{body}\n */"


@dataclass
class EvolveResult:
    """Result of evolving a single blind spot.

    Args:
        name: Method name.
        file_path: Source file path.
        line: Line number.
        best_fitness: Best Recall@1 achieved across all generations.
        best_variant: The winning JSDoc variant.
        generations_run: Number of generations actually executed.
        promoted: Whether any variant improved over the baseline.
    """

    name: str
    file_path: str
    line: int
    best_fitness: float
    best_variant: JSDocVariant | None
    generations_run: int
    promoted: bool


@dataclass
class GenerationResult:
    """Result of a single evolution generation.

    Args:
        generation: Generation index (0-based).
        population_size: Number of candidates evaluated.
        best_fitness: Best fitness in this generation.
        incumbent_fitness: Fitness of the incumbent (best so far).
        promoted: Whether the best candidate was promoted.
        best_variant: The best variant in this generation.
    """

    generation: int
    population_size: int
    best_fitness: float
    incumbent_fitness: float
    promoted: bool
    best_variant: JSDocVariant | None


# ----------------------------------------------------------------------- #
# Helper functions
# ----------------------------------------------------------------------- #


def _camel_to_words(name: str) -> str:
    """Convert a camelCase/PascalCase identifier to space-separated words.

    Args:
        name: Identifier like ``"handleCSVExport"``.

    Returns:
        Lowercased words like ``"handle csv export"``.
    """
    # Step 1: Handle acronym followed by word (CSVExport -> CSV Export)
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", name)
    # Step 2: Handle camelCase boundary (handleCSV -> handle CSV)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", s)
    # Step 3: Clean up and lowercase
    s = re.sub(r"\s+", " ", s).strip()
    return s.lower()


def _get_synonyms(name: str) -> list[str]:
    """Generate synonyms/related terms for a method name.

    Args:
        name: Method name.

    Returns:
        List of synonym strings.
    """
    words = _camel_to_words(name).split()
    synonyms: list[str] = []

    # Common verb synonyms (handles both base forms and acronyms)
    verb_map = {
        "get": ["fetch", "retrieve", "obtain", "read"],
        "set": ["update", "assign", "configure", "write"],
        "create": ["make", "build", "generate", "construct", "add"],
        "delete": ["remove", "destroy", "clear", "drop"],
        "update": ["modify", "edit", "change", "patch"],
        "handle": ["process", "manage", "deal with"],
        "export": ["output", "save", "write", "serialize"],
        "import": ["load", "read", "parse", "ingest"],
        "validate": ["check", "verify", "ensure"],
        "format": ["transform", "convert", "render"],
        "parse": ["decode", "interpret", "extract"],
        "init": ["initialize", "setup", "start"],
        "calc": ["compute", "calculate", "determine"],
        "send": ["dispatch", "transmit", "emit"],
        "recv": ["receive", "accept", "listen"],
        "csv": ["comma-separated", "tabular", "spreadsheet"],
        "json": ["object", "structured data"],
        "xml": ["markup", "hierarchical"],
        "html": ["rendered", "web"],
        "report": ["summary", "output", "document"],
        "data": ["information", "content", "records"],
        "file": ["document", "resource", "asset"],
    }

    for word in words:
        if word in verb_map:
            synonyms.extend(verb_map[word])

    return synonyms


def _detect_method_type(source_line: str) -> str:
    """Detect whether a source line is a function, arrow function, or method.

    Args:
        source_line: The source code line.

    Returns:
        ``"arrow"``, ``"method"``, or ``"function"``.
    """
    stripped = source_line.strip()
    if "=>" in stripped and ("const " in stripped or "let " in stripped or "var " in stripped):
        return "arrow"
    if re.search(r"^\s*(async\s+)?[a-zA-Z_][a-zA-Z0-9_]*\s*\(", stripped):
        if "function" not in stripped:
            return "method"
    return "function"


def _extract_params(source_line: str) -> list[str]:
    """Extract parameter names from a method signature.

    Args:
        source_line: The source code line containing the method signature.

    Returns:
        List of parameter names.
    """
    # Match content inside parentheses
    match = re.search(r"\(([^)]*)\)", source_line)
    if not match:
        return []

    params_str = match.group(1).strip()
    if not params_str:
        return []

    params = []
    for param in params_str.split(","):
        param = param.strip()
        if not param:
            continue
        # Handle default values
        param = param.split("=")[0].strip()
        # Handle destructuring
        if param.startswith(("{", "[")):
            continue
        # Handle type annotations (TypeScript)
        param = param.split(":")[0].strip()
        # Handle rest parameter
        if param.startswith("..."):
            param = param[3:]
        if param and re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", param):
            params.append(param)

    return params


# ----------------------------------------------------------------------- #
# JSDoc Generator
# ----------------------------------------------------------------------- #


class JSDocGenerator:
    """Generates JSDoc variants using mutation strategies.

    Each call to :meth:`generate` produces a variant by applying one or
    more mutation strategies to a base JSDoc template.
    """

    def __init__(self, rng: random.Random | None = None) -> None:
        self._rng = rng or random.Random()

    def generate(
        self,
        name: str,
        params: list[str] | None = None,
        method_type: str = "function",
        strategy: MutationStrategy | None = None,
    ) -> JSDocVariant:
        """Generate a JSDoc variant.

        Args:
            name: Method name.
            params: Parameter names.
            method_type: ``"function"``, ``"arrow"``, or ``"method"``.
            strategy: Specific strategy to use, or ``None`` for random.

        Returns:
            A ``JSDocVariant`` instance.
        """
        if strategy is None:
            strategy = self._sample_strategy()

        # Determine length
        length_class = self._rng.choice(list(LENGTH_VARIANTS.keys()))
        n_lines = LENGTH_VARIANTS[length_class]

        # Determine structure
        structure = self._rng.choice(STRUCTURE_VARIANTS)

        # Determine keyword density
        keyword_density = self._rng.choice(["synonyms", "generic"])

        # Determine position
        position = "above"  # default
        if method_type == "arrow":
            position = self._rng.choice(["above", "inline"])

        # Generate lines based on structure and length
        lines = self._build_lines(name, params or [], n_lines, structure, keyword_density)

        return JSDocVariant(
            strategy=strategy,
            lines=lines,
            length_class=length_class,
            structure=structure,
            keyword_density=keyword_density,
            position=position,
        )

    def _sample_strategy(self) -> MutationStrategy:
        """Sample a mutation strategy based on weights."""
        strategies = list(MutationStrategy)
        weights = [MUTATION_WEIGHTS[s.value] for s in strategies]
        return self._rng.choices(strategies, weights=weights, k=1)[0]

    def _build_lines(
        self,
        name: str,
        params: list[str],
        n_lines: int,
        structure: str,
        keyword_density: str,
    ) -> list[str]:
        """Build JSDoc lines based on structure and length constraints.

        Args:
            name: Method name.
            params: Parameter names.
            n_lines: Target number of lines.
            structure: ``"args_returns"``, ``"prose_only"``, or ``"mixed"``.
            keyword_density: ``"synonyms"`` or ``"generic"``.

        Returns:
            List of JSDoc content lines.
        """
        words = _camel_to_words(name)
        synonyms = _get_synonyms(name) if keyword_density == "synonyms" else []

        lines: list[str] = []

        if structure == "prose_only":
            # Prose-only: just a description
            desc = self._build_description(words, synonyms, keyword_density)
            lines.extend(self._wrap_text(desc, n_lines))

        elif structure == "args_returns":
            # Args/Returns/Raises structure
            desc = self._build_description(words, synonyms, keyword_density)
            lines.append(desc)

            if params and n_lines >= 3:
                for param in params[: n_lines - 2]:
                    lines.append(f"@param {{{param}}} — {param} parameter")

            if n_lines >= 2:
                lines.append("@returns {void}")

        else:  # mixed
            desc = self._build_description(words, synonyms, keyword_density)
            lines.append(desc)

            if params and n_lines >= 3:
                for param in params[: min(len(params), n_lines - 2)]:
                    lines.append(f"@param {{{param}}} — {param}")

            if n_lines >= 4 and params:
                lines.append("@returns {void}")

        # Truncate or pad to target length
        if len(lines) > n_lines:
            lines = lines[:n_lines]
        while len(lines) < n_lines:
            lines.append("")

        return lines

    def _build_description(self, words: str, synonyms: list[str], keyword_density: str) -> str:
        """Build a one-line description for the method.

        Args:
            words: Humanized method name.
            synonyms: List of synonym terms.
            keyword_density: ``"synonyms"`` or ``"generic"``.

        Returns:
            Description string.
        """
        if keyword_density == "synonyms" and synonyms:
            synonym = self._rng.choice(synonyms)
            templates = [
                f"{synonym.capitalize()} the {words}.",
                f"{synonym.capitalize()}s the {words}.",
                f"Used to {synonym} the {words}.",
            ]
        else:
            templates = [
                f"{words.capitalize()}.",
                f"Handles {words}.",
                f"Performs {words} operation.",
            ]
        return self._rng.choice(templates)

    def _wrap_text(self, text: str, n_lines: int) -> list[str]:
        """Wrap text into at most n_lines lines.

        Args:
            text: The text to wrap.
            n_lines: Maximum number of lines.

        Returns:
            List of wrapped lines.
        """
        if n_lines <= 1:
            return [text] if text else [""]

        words = text.split()
        if not words:
            return [""] * n_lines

        lines = []
        current = ""
        for word in words:
            if not current:
                current = word
            elif len(current) + 1 + len(word) <= 50:
                current += " " + word
            else:
                lines.append(current)
                current = word
        if current:
            lines.append(current)

        if len(lines) > n_lines:
            lines = lines[:n_lines]
        while len(lines) < n_lines:
            lines.append("")

        return lines

    def mutate_around(
        self,
        variant: JSDocVariant,
        name: str,
        params: list[str] | None = None,
        method_type: str = "function",
    ) -> JSDocVariant:
        """Create a new variant by mutating around an existing one.

        Preserves some attributes of the parent while randomly changing
        others — analogous to Gaussian perturbation in the tuner.

        Args:
            variant: The parent variant to mutate.
            name: Method name.
            params: Parameter names.
            method_type: ``"function"``, ``"arrow"``, or ``"method"``.

        Returns:
            A new ``JSDocVariant``.
        """
        # 50% chance to keep each attribute
        length_class = (
            variant.length_class
            if self._rng.random() < 0.5
            else self._rng.choice(list(LENGTH_VARIANTS.keys()))
        )
        structure = (
            variant.structure if self._rng.random() < 0.5 else self._rng.choice(STRUCTURE_VARIANTS)
        )
        keyword_density = (
            variant.keyword_density
            if self._rng.random() < 0.5
            else self._rng.choice(["synonyms", "generic"])
        )
        position = variant.position
        if method_type == "arrow" and self._rng.random() < 0.3:
            position = "inline" if position == "above" else "above"

        n_lines = LENGTH_VARIANTS[length_class]
        lines = self._build_lines(name, params or [], n_lines, structure, keyword_density)

        return JSDocVariant(
            strategy=self._sample_strategy(),
            lines=lines,
            length_class=length_class,
            structure=structure,
            keyword_density=keyword_density,
            position=position,
        )


# ----------------------------------------------------------------------- #
# DocEvolver
# ----------------------------------------------------------------------- #


class DocEvolver:
    """Evolutionary optimizer that generates and selects JSDoc for undocumented methods.

    For each blind spot (undocumented method), the evolver:
    1. Generates N JSDoc variants using mutation strategies.
    2. Patches each variant into the code, builds the index, runs a retrieval query.
    3. Scores each variant by Recall@1 (1/rank of correct file).
    4. Promotes the winning variant, mutates around it, repeats for G generations.
    5. After evolution, patches the winning JSDoc into the actual source files.

    Configurable via env:
      - NEURALMIND_DOC_EVOLVER_POPULATION (default 5)
      - NEURALMIND_DOC_EVOLVER_GENERATIONS (default 5)
      - NEURALMIND_DOC_EVOLVER_HYSTERESIS (default 0.05)

    Args:
        project_path: Path to the project root.
        blind_spots: List of undocumented methods to evolve JSDoc for.
        population_size: Candidates per generation (default 5).
        generations: Max generations per blind spot (default 5).
        hysteresis: Promotion margin (default 0.05).
        query_fn: Optional callable ``(project_path, query) -> list[str]`` that
            returns ranked source files for a query. Defaults to running
            ``neuralmind query`` via subprocess. Injected for testability.

    Raises:
        ValueError: If ``blind_spots`` is empty.
    """

    def __init__(
        self,
        project_path: str | Path,
        blind_spots: list[BlindSpot],
        population_size: int | None = None,
        generations: int | None = None,
        hysteresis: float | None = None,
        query_fn: Any = None,
    ) -> None:
        if not blind_spots:
            raise ValueError("blind_spots must not be empty")

        self.project_path = Path(project_path).resolve()
        self.blind_spots = blind_spots
        self.population_size = population_size or int(
            __import__("os").environ.get("NEURALMIND_DOC_EVOLVER_POPULATION", POPULATION_SIZE)
        )
        self.generations = generations or int(
            __import__("os").environ.get("NEURALMIND_DOC_EVOLVER_GENERATIONS", MAX_GENERATIONS)
        )
        self.hysteresis = hysteresis or float(
            __import__("os").environ.get("NEURALMIND_DOC_EVOLVER_HYSTERESIS", HYSTERESIS)
        )
        self.query_fn = query_fn
        self._rng = random.Random()
        self._generator = JSDocGenerator(self._rng)

        # Defensive coerce
        if self.hysteresis <= 0.0:
            log.warning("hysteresis must be positive, got %r — using default 0.05", self.hysteresis)
            self.hysteresis = 0.05
        if self.population_size <= 0:
            log.warning(
                "population_size must be positive, got %r — using default 5", self.population_size
            )
            self.population_size = POPULATION_SIZE
        if self.generations <= 0:
            log.warning("generations must be positive, got %r — using default 5", self.generations)
            self.generations = MAX_GENERATIONS

    # ------------------------------------------------------------------- #
    # Public API
    # ------------------------------------------------------------------- #

    def evolve(self) -> list[EvolveResult]:
        """Run evolution for all blind spots.

        Returns:
            List of ``EvolveResult``, one per blind spot. Fail-open:
            if evolution fails for a spot, the result has ``best_fitness=0.0``
            and ``best_variant=None``.
        """
        results: list[EvolveResult] = []
        for spot in self.blind_spots:
            try:
                result = self._evolve_one(spot)
                results.append(result)
            except Exception as exc:
                log.warning("evolution failed for %s:%s: %s", spot.file_path, spot.name, exc)
                results.append(
                    EvolveResult(
                        name=spot.name,
                        file_path=spot.file_path,
                        line=spot.line,
                        best_fitness=0.0,
                        best_variant=None,
                        generations_run=0,
                        promoted=False,
                    )
                )
        return results

    def patch_winners(self, results: list[EvolveResult]) -> list[str]:
        """Patch winning JSDoc variants into source files.

        Args:
            results: Results from :meth:`evolve`.

        Returns:
            List of file paths that were modified.
        """
        modified: list[str] = []
        for result in results:
            if result.best_variant is None:
                continue
            file_path = self.project_path / result.file_path
            if not file_path.exists():
                log.warning("source file not found: %s", file_path)
                continue
            try:
                self._patch_file(file_path, result.line, result.best_variant)
                modified.append(result.file_path)
            except Exception as exc:
                log.warning("failed to patch %s: %s", file_path, exc)
        return modified

    # ------------------------------------------------------------------- #
    # Evolution loop
    # ------------------------------------------------------------------- #

    def _evolve_one(self, spot: BlindSpot) -> EvolveResult:
        """Evolve JSDoc for a single blind spot.

        Args:
            spot: The blind spot to evolve.

        Returns:
            ``EvolveResult`` with the best variant found. If all
            evaluations fail, returns ``best_variant=None``.
        """
        # Detect method type and params from source if not provided
        source_params = spot.params
        source_method_type = spot.method_type
        if not source_params or source_method_type == "function":
            detected = self._inspect_source(spot)
            if detected:
                source_method_type = detected[0]
                if not source_params:
                    source_params = detected[1]

        # Generate initial population
        incumbent_variant = self._generator.generate(spot.name, source_params, source_method_type)
        incumbent_fitness = self._evaluate_candidate(spot, incumbent_variant)

        best_variant = incumbent_variant if incumbent_fitness > 0 else None
        best_fitness = incumbent_fitness
        promoted = False

        for _gen in range(self.generations):
            gen_best_variant = incumbent_variant
            gen_best_fitness = incumbent_fitness

            for _ in range(self.population_size):
                candidate = self._generator.mutate_around(
                    incumbent_variant, spot.name, source_params, source_method_type
                )
                candidate_fitness = self._evaluate_candidate(spot, candidate)
                if candidate_fitness > gen_best_fitness:
                    gen_best_fitness = candidate_fitness
                    gen_best_variant = candidate

            if self.promote_if_better(gen_best_fitness, incumbent_fitness):
                incumbent_variant = gen_best_variant
                incumbent_fitness = gen_best_fitness
                best_variant = gen_best_variant
                best_fitness = gen_best_fitness
                promoted = True
            else:
                if gen_best_fitness > best_fitness:
                    best_variant = gen_best_variant
                    best_fitness = gen_best_fitness

        return EvolveResult(
            name=spot.name,
            file_path=spot.file_path,
            line=spot.line,
            best_fitness=best_fitness,
            best_variant=best_variant,
            generations_run=self.generations,
            promoted=promoted,
        )

    def run_generation(
        self,
        spot: BlindSpot,
        incumbent_variant: JSDocVariant,
        incumbent_fitness: float,
        source_params: list[str],
        source_method_type: str,
    ) -> GenerationResult:
        """Run one generation of evolution for a blind spot.

        Exposed for testing and external orchestration. Each generation
        samples ``population_size`` candidates, evaluates them, and
        promotes the best if it beats the incumbent by the hysteresis
        margin.

        Args:
            spot: The blind spot.
            incumbent_variant: Current best variant.
            incumbent_fitness: Fitness of the incumbent.
            source_params: Parameter names.
            source_method_type: Method type.

        Returns:
            ``GenerationResult`` for this generation.
        """
        gen_best_variant = incumbent_variant
        gen_best_fitness = incumbent_fitness

        for _ in range(self.population_size):
            candidate = self._generator.mutate_around(
                incumbent_variant, spot.name, source_params, source_method_type
            )
            candidate_fitness = self._evaluate_candidate(spot, candidate)
            if candidate_fitness > gen_best_fitness:
                gen_best_fitness = candidate_fitness
                gen_best_variant = candidate

        promoted = self.promote_if_better(gen_best_fitness, incumbent_fitness)
        if promoted:
            incumbent_variant = gen_best_variant
            incumbent_fitness = gen_best_fitness

        return GenerationResult(
            generation=0,
            population_size=self.population_size,
            best_fitness=gen_best_fitness,
            incumbent_fitness=incumbent_fitness,
            promoted=promoted,
            best_variant=gen_best_variant,
        )

    def sample_candidate(
        self,
        incumbent: JSDocVariant,
        name: str,
        params: list[str],
        method_type: str,
    ) -> JSDocVariant:
        """Sample a candidate variant by mutating around the incumbent.

        Args:
            incumbent: The current best variant.
            name: Method name.
            params: Parameter names.
            method_type: Method type.

        Returns:
            A new ``JSDocVariant``.
        """
        return self._generator.mutate_around(incumbent, name, params, method_type)

    def evaluate_candidate(
        self,
        spot: BlindSpot,
        variant: JSDocVariant,
    ) -> float:
        """Evaluate a JSDoc variant against the retrieval fitness function.

        Patches the variant into the source, runs a natural-language query,
        and scores by Recall@1 (1/rank of correct file).

        Args:
            spot: The blind spot.
            variant: The JSDoc variant to evaluate.

        Returns:
            Fitness score in [0, 1].
        """
        return self._evaluate_candidate(spot, variant)

    def promote_if_better(self, candidate_fitness: float, incumbent_fitness: float) -> bool:
        """Check if candidate should be promoted over incumbent.

        Args:
            candidate_fitness: Fitness of the candidate.
            incumbent_fitness: Fitness of the incumbent.

        Returns:
            ``True`` if candidate beats incumbent by hysteresis margin.
        """
        return candidate_fitness > incumbent_fitness * (1.0 + self.hysteresis)

    # ------------------------------------------------------------------- #
    # Internal evaluation
    # ------------------------------------------------------------------- #

    def _evaluate_candidate(self, spot: BlindSpot, variant: JSDocVariant) -> float:
        """Score a variant by patching, querying, and measuring Recall@1.

        Patches the JSDoc into the actual source file, rebuilds the index,
        runs a retrieval query, then restores the original content.

        Args:
            spot: The blind spot.
            variant: The JSDoc variant.

        Returns:
            Recall@1 score (1/rank, 0.0 if not found).
        """
        file_path = self.project_path / spot.file_path
        if not file_path.exists():
            log.warning("source file not found: %s", file_path)
            return 0.0

        # Read original source
        original_content = file_path.read_text(encoding="utf-8")
        lines = original_content.splitlines()

        # Find the actual line (handle offset from AST)
        insert_line = self._find_method_line(lines, spot)
        if insert_line is None:
            log.warning("could not locate method %s in %s", spot.name, spot.file_path)
            return 0.0

        # Patch in the JSDoc
        jsdoc_lines = variant.text.splitlines()
        patched_lines = lines[:insert_line] + jsdoc_lines + lines[insert_line:]
        patched_content = "\n".join(patched_lines) + "\n"

        # Write patched content to actual source file, rebuild index, query, restore
        # Use atomic file ops: backup first, restore via os.replace() to prevent
        # data corruption if the process is killed (SIGKILL, OOM) between write and finally.
        import shutil

        backup_path = file_path.with_suffix(file_path.suffix + ".bak")
        shutil.copy2(file_path, backup_path)
        try:
            file_path.write_text(patched_content, encoding="utf-8")

            # Rebuild index with patched content
            build_result = subprocess.run(
                [sys.executable, "-m", "neuralmind.cli", "build", str(self.project_path)],
                capture_output=True,
                text=True,
                timeout=120,
            )
            if build_result.returncode != 0:
                log.warning("neuralmind build failed: %s", build_result.stderr)
                return 0.0

            # Build query from method name
            query = _camel_to_words(spot.name)

            # Run query
            ranked_files = self._run_query(query)

            # Score by rank of correct file
            target_file = spot.file_path.replace("\\", "/")
            for rank, filepath in enumerate(ranked_files, start=1):
                if filepath.replace("\\", "/") == target_file:
                    return 1.0 / rank

            return 0.0

        except Exception as exc:
            log.warning("evaluation failed for %s: %s", spot.name, exc)
            return 0.0

        finally:
            # Always restore original content atomically from backup
            backup_path.replace(file_path)

    def _run_query(self, query: str) -> list[str]:
        """Run a retrieval query and return ranked source files.

        Uses the injected ``query_fn`` if provided (for testing), otherwise
        shells out to ``neuralmind query`` and parses the JSON output.

        Args:
            query: Natural-language query string.

        Returns:
            List of source file paths, ranked by relevance.
        """
        if self.query_fn is not None:
            return self.query_fn(str(self.project_path), query)

        # Shell out to neuralmind query
        try:
            result = subprocess.run(
                [sys.executable, "-m", "neuralmind.cli", "query", str(self.project_path), query, "--json"],
                capture_output=True,
                text=True,
                timeout=60,
            )
            if result.returncode != 0:
                log.warning("neuralmind query failed: %s", result.stderr)
                return []

            data = json.loads(result.stdout)
            context = data.get("context", "")

            # Parse file paths from markdown search results
            # Pattern: "File: path/to/file.ext" or "**file** (score: N)\n   Type: code\n   File: path"
            # Use permissive regex that captures paths with spaces by requiring
            # the path to end with a recognized code extension.
            code_exts = (
                ".ts",
                ".tsx",
                ".py",
                ".js",
                ".jsx",
                ".go",
                ".rs",
                ".java",
                ".cs",
                ".cpp",
                ".c",
                ".rb",
                ".php",
            )
            file_pattern = re.compile(
                r"File:\s+([^\s,\n]+?\.(?:" + "|".join(ext.lstrip(".") for ext in code_exts) + "))"
            )
            files = []
            for match in file_pattern.finditer(context):
                f = match.group(1).strip()
                # Filter: require BOTH path separator AND recognized code extension
                if "/" in f and f.endswith(code_exts):
                    files.append(f)
            return files

        except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError) as exc:
            log.warning("query execution failed: %s", exc)
            return []

    def _find_method_line(self, lines: list[str], spot: BlindSpot) -> int | None:
        """Find the line index where JSDoc should be inserted.

        Searches around the expected line number for the method signature.

        Args:
            lines: Source file lines.
            spot: The blind spot.

        Returns:
            0-based line index for insertion, or ``None`` if not found.
        """
        # Search within a window around the expected line
        window = 10
        start = max(0, spot.line - window - 1)
        end = min(len(lines), spot.line + window)

        # Pattern to match the method name
        name_pattern = re.compile(r"\b" + re.escape(spot.name) + r"\b")

        for i in range(start, end):
            if name_pattern.search(lines[i]):
                # Check if there's already a JSDoc comment above
                if i > 0 and lines[i - 1].strip().endswith("*/"):
                    return None  # Already documented
                return i

        # Fallback: try the exact line
        if 0 <= spot.line - 1 < len(lines):
            return spot.line - 1

        return None

    # ------------------------------------------------------------------- #
    # Source inspection
    # ------------------------------------------------------------------- #

    def _inspect_source(self, spot: BlindSpot) -> tuple[str, list[str]] | None:
        """Inspect source file to detect method type and parameters.

        Args:
            spot: The blind spot.

        Returns:
            Tuple of ``(method_type, params)`` or ``None`` if file not found.
        """
        file_path = self.project_path / spot.file_path
        if not file_path.exists():
            return None

        try:
            lines = file_path.read_text(encoding="utf-8").splitlines()
            for _i, line in enumerate(lines):
                if spot.name in line:
                    method_type = _detect_method_type(line)
                    params = _extract_params(line)
                    return method_type, params
        except Exception:
            pass

        return None

    # ------------------------------------------------------------------- #
    # Patching
    # ------------------------------------------------------------------- #

    def _patch_file(self, file_path: Path, line: int, variant: JSDocVariant) -> None:
        """Patch a JSDoc variant into a source file.

        Args:
            file_path: Path to the source file.
            line: 1-based line number of the method.
            variant: The JSDoc variant to insert.

        Raises:
            FileNotFoundError: If the file doesn't exist.
            ValueError: If the method can't be located.
        """
        content = file_path.read_text(encoding="utf-8")
        lines = content.splitlines()

        # Find the method by line number
        insert_idx = self._find_method_line_by_number(lines, line)
        if insert_idx is None:
            raise ValueError(f"could not locate method at line {line}")

        # Check if already documented
        if insert_idx > 0 and lines[insert_idx - 1].strip().endswith("*/"):
            return  # Already has JSDoc

        # Insert JSDoc
        jsdoc_lines = variant.text.splitlines()
        new_lines = lines[:insert_idx] + jsdoc_lines + lines[insert_idx:]
        new_content = "\n".join(new_lines) + "\n"

        file_path.write_text(new_content, encoding="utf-8")

    def _find_method_line_by_number(self, lines: list[str], line: int) -> int | None:
        """Find the 0-based line index for a 1-based line number.

        Args:
            lines: Source file lines.
            line: 1-based line number.

        Returns:
            0-based index, or ``None`` if out of range.
        """
        idx = line - 1
        if 0 <= idx < len(lines):
            return idx
        return None


# ----------------------------------------------------------------------- #
# AST Audit Helper
# ----------------------------------------------------------------------- #


def audit_blind_spots(project_path: str | Path) -> list[BlindSpot]:
    """Scan a project for undocumented public methods.

    Walks the source tree, parses JS/TS files, and identifies public
    methods/functions lacking JSDoc comments. This is a lightweight
    heuristic audit — for a full AST audit, use a proper parser.

    Args:
        project_path: Path to the project root.

    Returns:
        List of ``BlindSpot`` instances for undocumented methods.
    """
    project_path = Path(project_path)
    spots: list[BlindSpot] = []

    skip_dirs = {
        "node_modules",
        ".git",
        "dist",
        "build",
        ".next",
        "coverage",
        "__pycache__",
        ".venv",
        "venv",
        ".neuralmind",
        "graphify-out",
    }

    source_extensions = {".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"}

    for root, dirs, files in __import__("os").walk(project_path):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for fname in files:
            if not any(fname.endswith(ext) for ext in source_extensions):
                continue
            file_path = __import__("pathlib").Path(root) / fname
            rel_path = file_path.relative_to(project_path)
            try:
                content = file_path.read_text(encoding="utf-8", errors="ignore")
                spots.extend(_scan_file_for_blind_spots(content, str(rel_path)))
            except Exception:
                continue

    return spots


def _scan_file_for_blind_spots(content: str, file_path: str) -> list[BlindSpot]:
    """Scan a single file for undocumented methods.

    Args:
        content: File content.
        file_path: Relative file path.

    Returns:
        List of ``BlindSpot`` instances.
    """
    spots: list[BlindSpot] = []
    lines = content.splitlines()

    # Patterns for method/function declarations
    patterns = [
        # function name(...) or export function name(...)
        re.compile(r"^\s*(?:export\s+)?(?:async\s+)?function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\("),
        # const name = (...) => or const name = function(...)
        re.compile(
            r"^\s*(?:export\s+)?(?:const|let|var)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?(?:\(|function\b)"
        ),
        # class method: name(...) {
        re.compile(r"^\s*(?:async\s+)?([a-zA-Z_][a-zA-Z0-9_]*)\s*\([^)]*\)\s*\{"),
    ]

    for i, line in enumerate(lines):
        for pattern in patterns:
            match = pattern.match(line)
            if not match:
                continue

            name = match.group(1)

            # Skip common non-method patterns
            if name in ("if", "while", "for", "switch", "catch", "return"):
                continue

            # Check if preceded by JSDoc
            has_jsdoc = False
            for j in range(i - 1, max(i - 10, -1), -1):
                if j < 0:
                    break
                stripped = lines[j].strip()
                if stripped.endswith("*/"):
                    has_jsdoc = True
                    break
                if stripped and not stripped.startswith("//"):
                    break

            if has_jsdoc:
                continue

            # Detect method type and params
            method_type = _detect_method_type(line)
            params = _extract_params(line)

            spots.append(
                BlindSpot(
                    name=name,
                    file_path=file_path,
                    line=i + 1,  # 1-based
                    method_type=method_type,
                    params=params,
                )
            )
            break  # Only match first pattern per line

    return spots
