"""session_summaries.py — Periodic, semantically-recallable session digests.

NeuralMind has no session memory: each query is stateless, and the agent
has no way to recall what was done in a previous session. This module
adds periodic session summaries that are:
- Generated every N tool calls (default 25)
- Stored as markdown files under .neuralmind/summaries/
- Semantically recallable via the existing vector index
- Automatically pruned (max 100 per project)

Each summary captures:
- What was done (files modified, commands run)
- Key decisions made
- Files touched (for co-access edge learning)
- Timestamp and session ID

The summary is generated by the agent itself (via a prompt) and written
to disk. It is then ingested into the vector index so future queries
can retrieve relevant past session context.

Design:
- Stdlib only (no new dependencies)
- Markdown format for human readability
- Front-mattered YAML for machine parsing
- Content-hash dedup (skip if unchanged)
- Auto-prune oldest when exceeding max_kept
"""

from __future__ import annotations

import hashlib
import logging
import os
import time
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

# Defaults (match lean-ctx)
DEFAULT_EVERY_N_TURNS = 25
DEFAULT_MAX_KEPT = 100

# Summary front-matter template
SUMMARY_TEMPLATE = """---
session_id: {session_id}
timestamp: {timestamp}
tool_calls: {tool_call_count}
files_touched: {files_touched}
title: {title}
---

# Session Summary

## What was done
{what_was_done}

## Key decisions
{key_decisions}

## Files touched
{files_list}

## Commands run
{commands_list}

## Notes
{notes}
"""


def _env_int(name: str, default: int) -> int:
    """Read an int from the environment, falling back on unset/malformed."""
    try:
        return int(os.environ[name])
    except (KeyError, ValueError):
        return default


def _env_bool(name: str, default: bool) -> bool:
    """Read a bool from the environment, falling back on unset/malformed."""
    val = os.environ.get(name, "").strip().lower()
    if val in ("1", "true", "yes", "on"):
        return True
    if val in ("0", "false", "no", "off"):
        return False
    return default


@dataclass
class SessionSummaryConfig:
    """Configuration for session summaries."""

    enabled: bool = _env_bool("NEURALMIND_SESSION_SUMMARIES", True)
    every_n_turns: int = _env_int("NEURALMIND_SUMMARY_EVERY_N_TURNS", DEFAULT_EVERY_N_TURNS)
    max_kept: int = _env_int("NEURALMIND_SUMMARY_MAX_KEPT", DEFAULT_MAX_KEPT)


@dataclass
class SessionSummary:
    """A single session summary."""

    session_id: str
    timestamp: float
    tool_call_count: int
    files_touched: list[str]
    title: str
    what_was_done: str
    key_decisions: list[str]
    commands_run: list[str]
    notes: str = ""

    def to_markdown(self) -> str:
        """Render as front-mattered markdown."""
        return SUMMARY_TEMPLATE.format(
            session_id=self.session_id,
            timestamp=self.timestamp,
            tool_call_count=self.tool_call_count,
            files_touched=", ".join(self.files_touched) if self.files_touched else "none",
            title=self.title,
            what_was_done=self.what_was_done,
            key_decisions=(
                "\n".join(f"- {d}" for d in self.key_decisions) if self.key_decisions else "None"
            ),
            files_list=(
                "\n".join(f"- {f}" for f in self.files_touched) if self.files_touched else "None"
            ),
            commands_list=(
                "\n".join(f"- {c}" for c in self.commands_run) if self.commands_run else "None"
            ),
            notes=self.notes or "None",
        )

    def content_hash(self) -> str:
        """Content hash for dedup."""
        content = f"{self.session_id}:{self.timestamp}:{self.what_was_done}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "tool_call_count": self.tool_call_count,
            "files_touched": self.files_touched,
            "title": self.title,
            "what_was_done": self.what_was_done,
            "key_decisions": self.key_decisions,
            "commands_run": self.commands_run,
            "notes": self.notes,
        }


class SessionTracker:
    """Track session state and generate summaries.

    Usage:
        tracker = SessionTracker(project_path)
        tracker.record_tool_call(files_touched=["foo.py"], command="pytest")
        if tracker.should_summarize():
            summary = tracker.generate_summary()
            tracker.write_summary(summary)
    """

    def __init__(
        self,
        project_path: str | Path,
        config: SessionSummaryConfig | None = None,
        session_id: str | None = None,
    ):
        self.project_path = Path(project_path)
        self.config = config or SessionSummaryConfig()
        self.session_id = session_id or self._generate_session_id()
        self.tool_call_count = 0
        self.files_touched: list[str] = []
        self.commands_run: list[str] = []
        self.decisions: list[str] = []
        self._last_summary_hash: str | None = None
        self._summaries_dir = self.project_path / ".neuralmind" / "summaries"

    def _generate_session_id(self) -> str:
        """Generate a unique session ID."""
        return f"session-{int(time.time())}-{os.getpid()}"

    def record_tool_call(
        self,
        files_touched: list[str] | None = None,
        command: str | None = None,
        decision: str | None = None,
    ) -> None:
        """Record a tool call for session tracking."""
        self.tool_call_count += 1
        if files_touched:
            for f in files_touched:
                if f not in self.files_touched:
                    self.files_touched.append(f)
        if command and command not in self.commands_run:
            self.commands_run.append(command)
        if decision and decision not in self.decisions:
            self.decisions.append(decision)

    def should_summarize(self) -> bool:
        """Check if a summary should be generated."""
        if not self.config.enabled:
            return False
        return self.tool_call_count > 0 and self.tool_call_count % self.config.every_n_turns == 0

    def generate_summary(
        self, title: str = "", what_was_done: str = "", notes: str = ""
    ) -> SessionSummary:
        """Generate a session summary from tracked state."""
        return SessionSummary(
            session_id=self.session_id,
            timestamp=time.time(),
            tool_call_count=self.tool_call_count,
            files_touched=list(self.files_touched),
            title=title or f"Session {self.session_id}",
            what_was_done=what_was_done or f"Completed {self.tool_call_count} tool calls",
            key_decisions=list(self.decisions),
            commands_run=list(self.commands_run),
            notes=notes,
        )

    def write_summary(self, summary: SessionSummary) -> Path | None:
        """Write a summary to disk, with dedup.

        Returns the path written, or None if deduped (unchanged).
        """
        # Dedup check
        content_hash = summary.content_hash()
        if content_hash == self._last_summary_hash:
            logger.debug("[session_summaries] skipping duplicate summary")
            return None

        # Ensure directory exists
        self._summaries_dir.mkdir(parents=True, exist_ok=True)

        # Write file
        filename = f"{summary.session_id}-{int(summary.timestamp)}.md"
        path = self._summaries_dir / filename
        path.write_text(summary.to_markdown(), encoding="utf-8")

        self._last_summary_hash = content_hash
        logger.info(
            "[session_summaries] wrote %s (%d files, %d commands)",
            path,
            len(summary.files_touched),
            len(summary.commands_run),
        )

        # Prune old summaries
        self._prune_old_summaries()

        return path

    def _prune_old_summaries(self) -> None:
        """Remove oldest summaries when exceeding max_kept."""
        if not self._summaries_dir.exists():
            return

        summaries = sorted(self._summaries_dir.glob("*.md"), key=lambda p: p.stat().st_mtime)
        if len(summaries) > self.config.max_kept:
            to_remove = summaries[: len(summaries) - self.config.max_kept]
            for old in to_remove:
                old.unlink()
                logger.debug("[session_summaries] pruned %s", old)

    def list_summaries(self) -> list[dict]:
        """List all summaries for this project."""
        if not self._summaries_dir.exists():
            return []

        summaries = []
        for path in sorted(self._summaries_dir.glob("*.md"), key=lambda p: p.stat().st_mtime):
            try:
                text = path.read_text(encoding="utf-8")
                # Parse front-matter
                if text.startswith("---"):
                    end = text.find("---", 3)
                    if end != -1:
                        fm = text[3:end].strip()
                        summary = {}
                        for line in fm.split("\n"):
                            if ":" in line:
                                k, v = line.split(":", 1)
                                summary[k.strip()] = v.strip()
                        summary["path"] = str(path)
                        summaries.append(summary)
            except Exception:
                continue

        return summaries

    def get_recent_summaries(self, n: int = 5) -> list[dict]:
        """Get the N most recent summaries."""
        all_summaries = self.list_summaries()
        return all_summaries[-n:] if len(all_summaries) > n else all_summaries
